import Foundation
import Testing

@testable import MixNerd

struct AudioFileTests {

  @Test
  func testCueFileContent_withTracklist() {
    let audioFileURL = URL(fileURLWithPath: "/tmp/test-audio.mp3")
    let audioFile = AudioFile(fromFilePath: audioFileURL)

    let date = Date(year: 2025, month: 2, day: 11)
    var tracklist = Tracklist()
    tracklist.artist = "Vini Vici"
    tracklist.title = "Dreamstate Radio 077"
    tracklist.date = date
    tracklist.tracks = [
      Track(time: Time(string: "00:00"), artist: "Artist 1", title: "Track 1"),
      Track(time: Time(string: "05:30"), artist: "Artist 2", title: "Track 2"),
      Track(time: Time(string: "67:15"), artist: "Artist 3", title: "Track 3"),
    ]

    audioFile.tracklist = tracklist

    let content = audioFile.cueFile().content()

    // Extract the dynamic date line
    let lines = content.components(separatedBy: "\n")
    let dateLine = lines[1]  // "REM Generated on ..."

    let expected = """
      REM Generated by https://github.com/elliotchance/MixNerd
      \(dateLine)
      PERFORMER "Vini Vici"
      TITLE "2025-02-11 Dreamstate Radio 077"
      FILE "test-audio.mp3" MP3
        TRACK 01 AUDIO
          PERFORMER "Artist 1"
          TITLE "Track 1"
          INDEX 01 0:00:00
        TRACK 02 AUDIO
          PERFORMER "Artist 2"
          TITLE "Track 2"
          INDEX 01 5:30:00
        TRACK 03 AUDIO
          PERFORMER "Artist 3"
          TITLE "Track 3"
          INDEX 01 67:15:00
      """

    #expect(content == expected)
  }
}
