import Foundation
import Testing

@testable import MixNerd

struct CueFileTests {

  @Test
  func testContent() {
    let cueFile = CueFile(
      performer: "Vini Vici",
      title: "Dreamstate Radio 077",
      file: "test-audio.mp3",
      tracks: [
        CueTrack(performer: "Artist 1", title: "Track 1", time: .seconds(0)),
        CueTrack(performer: "Artist 2", title: "Track 2", time: .seconds(5.5 * 60)),
        CueTrack(performer: "Artist 3", title: "Track 3", time: .seconds(67.25 * 60)),
      ],
    )

    let content = cueFile.content()

    // Extract the dynamic date line
    let lines = content.components(separatedBy: "\n")
    let dateLine = lines[1]  // "REM Generated on ..."

    let expected = """
      REM Generated by https://github.com/elliotchance/MixNerd
      \(dateLine)
      PERFORMER "Vini Vici"
      TITLE "Dreamstate Radio 077"
      FILE "test-audio.mp3" MP3
        TRACK 01 AUDIO
          PERFORMER "Artist 1"
          TITLE "Track 1"
          INDEX 01 0:00:00
        TRACK 02 AUDIO
          PERFORMER "Artist 2"
          TITLE "Track 2"
          INDEX 01 5:30:00
        TRACK 03 AUDIO
          PERFORMER "Artist 3"
          TITLE "Track 3"
          INDEX 01 67:15:00
      """

    #expect(content == expected)
  }
}
