import Foundation

class CueFile {
  var performer: String
  var title: String
  var file: String
  var tracks: [CueTrack] = []

  init(performer: String, title: String, file: String, tracks: [CueTrack]) {
    self.performer = performer
    self.title = title
    self.file = file
    self.tracks = tracks
  }

  func content() -> String {
    var lines = [
      "REM Generated by https://github.com/elliotchance/MixNerd",
      "REM Generated on \(ISO8601DateFormatter().string(from: Foundation.Date()))",
      "PERFORMER \"\(performer)\"",
      "TITLE \"\(title)\"",
      "FILE \"\(file)\" MP3",
    ]

    var i = 1
    for track in tracks {
      lines.append(track.content(at: i))
      i += 1
    }

    return lines.joined(separator: "\n")
  }
}
